# Generated by Django 4.2.7 on 2023-11-08 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField()),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Discount Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Rate (%)')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='TaxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tax Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Rate (%)')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('unit', models.CharField(choices=[('Each (EA)', 'Each (EA)'), ('Kilogram (KG)', 'Kilogram (KG)'), ('Gram (G)', 'Gram (G)'), ('Liter (L)', 'Liter (L)'), ('Milliliter (ML)', 'Milliliter (ML)'), ('Meter (M)', 'Meter (M)'), ('Centimeter (CM)', 'Centimeter (CM)'), ('Square Meter (M²)', 'Square Meter (M²)'), ('Cubic Meter (M³)', 'Cubic Meter (M³)'), ('Pack (PK)', 'Pack (PK)'), ('Pair (PR)', 'Pair (PR)'), ('Box (BX)', 'Box (BX)'), ('Case (CS)', 'Case (CS)'), ('Dozen (DOZ)', 'Dozen (DOZ)'), ('Bundle (BUN)', 'Bundle (BUN)')], max_length=40, verbose_name='Unit')),
                ('sku', models.CharField(max_length=15, unique=True, verbose_name='SKU')),
                ('min_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Qty')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], max_length=10, verbose_name='Status')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.category', verbose_name='Category')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.discountmodel', verbose_name='Discount Type')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.subcategory', verbose_name='Sub Category')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.taxmodel', verbose_name='Tax')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
