# Generated by Django 4.2.7 on 2023-11-08 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posapp', '0002_alter_product_brand_alter_product_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Product Name'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'sku', 'name')},
        ),
    ]
